apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: argoCD
    repoURL: 'https://github.com/ranvirkardhanraj/argoCD.git'
    targetRevision: HEAD
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
